[phases.setup]
nixPkgs = ["php", "php-extensions.imap", "php-extensions.gd", "php-extensions.mbstring", "php-extensions.xml", "php-extensions.zip", "php-extensions.curl", "php-extensions.json", "php-extensions.openssl", "php-extensions.pdo", "php-extensions.pdo_mysql", "php-extensions.mysqli", "php-extensions.iconv", "php-extensions.fileinfo", "php-extensions.phar", "php-extensions.spl", "php-extensions.tokenizer", "php-extensions.ctype", "php-extensions.session", "php-extensions.filter", "php-extensions.hash", "php-extensions.mcrypt", "php-extensions.openssl", "php-extensions.pcre", "php-extensions.reflection", "php-extensions.spl", "php-extensions.standard", "php-extensions.xmlreader", "php-extensions.xmlwriter", "php-extensions.zlib"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ." 